version: '3.8'
services:
  web:
    image: docker-redditclone-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./functions:/app/funtions
      - ./public:app/public
      - ./src:app/src
    # user: root
    # build:
    #   context: "./"
    #   target: runner
    # volumes:
    #   - .:/reddit-clone
    # command: yarn dev
    # ports:
    #   - "3000:3000"
    # environment:
    #   NODE_ENV: development
